### ISSUE TITLE
Add/offer do not respect queue capacity

### ISSUE THREAD

**Issue by ThomasBassa** [ThomasBassa/qa-team-voltron#9]
The testAdd I wrote fails, even after adding the throw specified by the add contract.

Playing around with the tests a bit, I notice you can add _at least_ 5 elements to the size 3 queue without it throwing any exception. This is not intended behavior, to my knowledge...

**Comment by GregC123456789** [comment]
Edited the code. It was a misplaced comment on the if statement.

**Comment by ThomasBassa** [comment]
`testOffer` now fails instead of `testAdd`. First assert gets zero instead of 3. I remember hearing from someone else that "head" and "tail" were semantically reversed... Dangit @GregC123456789 you didn't do as much as you think you did XD

**Comment by GregC123456789** [comment]
It should be reverse. The offer tests that are in there have the bug.

It should offer 0, 1, 2, then try to offer 3. Since the bug was in the if
statement the junit test would have 3 at queue position 0.

**Comment by ThomasBassa** [comment]
The test needs to be corrected then.

Could probably just copy/paste `testAdd`, replace adds with offers, and replace the exception stuff with an assertFalse.

I'm past the point where I need to get some sleep... So please take care of that. The test should do what the docs say they do (per #6) and they should all pass.

Please write slightly more descriptive commit messages, and don't forget to [include `closes #9` or similar in said commit message](https://help.github.com/articles/closing-issues-via-commit-messages/).

G'night!

**Comment by GregC123456789** [comment]
Will do, G'night see you in class
